import sys
import argparse
import pysam
import gzip
from collections import defaultdict
from timeit import default_timer as timer
from subprocess import Popen, PIPE

parser = argparse.ArgumentParser(
                    prog='bam2fastq_10x_v3.1_STARsolo.py',
                    description='Converts a 10x v3.1 scRNA-seq bams generated by STARsolo back to fastq')

parser.add_argument("-i", "--input",  required=True, help="The input BAM file to convert")
parser.add_argument("-o", "--output", required=True, help="Prefix for the output files")
parser.add_argument("-p", "--ncpu", required=False, type=int, default=1, help="The number of CPU cores to use")

args = parser.parse_args()

infile         = args.input
outfile_prefix = args.output
ncpu           = args.ncpu
            
def revcomp_DNA(dna, extended=True):
    '''
    Reverse complement of input DNA sequence.

    Parameters
    ----------
    dna : str
        DNA sequences made of 'A', 'C', 'G', 'T', 'N' or 'X'

    extended : bool
        Support full IUPAC nucleotides.

    Examples
    --------
    >>> revcomp_DNA('AACGTG')
    'CACGTT'
    '''
    if extended:
        complement = {'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A', 'Y': 'R', 'R': 'Y', 'S': 'W', 'W': 'S', 'K': 'M', 'M': 'K', 'B': 'V', 'V': 'B', 'D': 'H', 'H': 'D', 'N': 'N', '.':'.', '*':'*'}
    else:
        complement = {'A':'T','C':'G','G':'C','T':'A','N':'N','X':'X'}

    seq = dna.replace(' ','').upper()
    if ',' not in seq:
        return ''.join([complement[base] for base in reversed(seq)])
    else:
        seqs = seq.split(',')
        comp_seqs = []
        for s in seqs:
            comp_seqs.append(''.join([complement[base] for base in reversed(s)]))
        return ','.join(comp_seqs)

            
SAMFILE = pysam.AlignmentFile(infile, "rb", threads=ncpu)
R1file = open(outfile_prefix + "_S1_L001_R1_001.fastq.gz", "wb")
R2file = open(outfile_prefix + "_S1_L001_R2_001.fastq.gz", "wb")
R1 = Popen(["gzip"], stdin=PIPE, stdout=R1file, text=True)
R2 = Popen(["gzip"], stdin=PIPE, stdout=R2file, text=True)

print("Processing reads...", file = sys.stderr)
start = timer()
nreads = 0
for read in SAMFILE.fetch(until_eof = True):
  nreads += 1
  if nreads % 50000000 == 0:
    end = timer()
    print("Processed " + str(nreads) + 
      " reads in " + 
      str(round(end-start,2)) + " seconds", file = sys.stderr)
      
  readname = "@" + read.query_name
  
  if (read.is_reverse):
    R2sequence = revcomp_DNA(read.query_sequence)
    R2quality = pysam.qualities_to_qualitystring(read.query_qualities)[::-1]
  else:
    R2sequence = read.query_sequence
    R2quality = pysam.qualities_to_qualitystring(read.query_qualities)
  
  R1sequence = str(read.get_tag("sS")) 
  R1quality = str(read.get_tag("sQ")) 
  
  R1.stdin.write(readname + "\n" +
    R1sequence      + "\n" +
    "+"             + "\n" +
    R1quality       + "\n")
  
  R2.stdin.write(readname + "\n" +
    R2sequence      + "\n" +
    "+"             + "\n" +
    R2quality       + "\n")

end = timer()
print("Done in " + str(round(end-start,2)) + " seconds", file = sys.stderr)

R1.stdin.close()
R2.stdin.close()

R1file.close()
R2file.close()
